### ISSUE TITLE
FP article links for review

### ISSUE THREAD

**Issue by jamesdunham** [georgetown-cset/article-linking#45]
I came across a few titles and abstracts that didn't seem to belong together, so I pulled the contributing metadata and saw they were from different original articles that had been FP-linked.

We expect this to happen of course, rarely, but what caught my attention is that I don't see why they'd be linked, based on my understanding of our linkage criteria ([here](https://eto.tech/dataset-docs/mac/#deduplicating-articles)). Any ideas on what I'm missing? I dropped the metadata for the papers [here](https://docs.google.com/spreadsheets/d/19351yHIcGiMyES0oUgZg1wEpak0oo3dHytKRIPzVzpE/edit?usp=sharing).

**Comment by jmelot** [comment]
This is definitely weird. I'm in the process of tracking it down and will post my findings tomorrow... thanks for the good examples!

**Comment by jmelot** [comment]
This is what I've found so far:

1. These links only appear because they were linked in a previous article linkage run. They do not appear in current rule-based or simhash outputs
2. The incorrect linkages do not occur in our experiment with a reduced set of input datasets
3. The incorrect linkages _are_ present as of our first run with our current set of datasets (from the 2023-08-01 literature.sources snapshot)

One guess I had for what was going on is that some vendors provide links to articles in other datasets, and that is another way we link articles together. If a vendor later corrected those links, that could result in the cases we see here. That said, I have not been able to show that this was what was going on in this case.

I will send a few other comments on slack. I think the best course of action is for me to update the linkage code to discard previous linkages that we can no longer replicate (obvious in retrospect... at the time I was thinking more about articles merging over time as more metadata came in than the possibility that articles could ever _unmerge_!). I don't expect this to be very many articles, but I will verify that is the case before triggering downstream tasks.
